### ISSUE TITLE
Armory uploads for WoTLK realms (Lordareon)

### ISSUE THREAD

**Issue by mario8000** [Geigerkind/Legacy-Logs-Bugtracker#38]
Hey bud, just started using your system today great job by the way!

One problem I noticed so far:
When trying to view the armory for the Toons i have inspected on the Lordareon realm, the I get taken to a bad link. Use my character name Xenima as an example.

**Comment by mario8000** [comment]
Using version .27 of the launcher and latest from the website for the armory/dps mate addon. Raid stats seem to be uploading fine, but armory is not working.

**Comment by Geigerkind** [comment]
Will look into it tomorrow. I am getting very few data from wotlk unfortunately.

Did you use the LegacyLogsArmory addon?

**Comment by mario8000** [comment]
Yes i used the latest version of the LegacyLogsArmory addon. I noticed there is only a .TOC and .LUA addon in the zip file. is this correct?

**Comment by mario8000** [comment]
Any updates from this? i have been sort of promoting your site for Warmanes realms as well, hope i can get more people to use :)

**Comment by Geigerkind** [comment]
Could you send me a screenshot of the warmane realmlist in the character screen, where I can see all server names?

**Comment by mario8000** [comment]
![lordaeron servers](https://cloud.githubusercontent.com/assets/24818108/21583965/1d35b238-d064-11e6-80c2-901f86814b7f.PNG)

**Comment by Geigerkind** [comment]
Ok, can u check if it is still not being processed?

**Comment by mario8000** [comment]
This seems to have fixed the issue thanks :)

**Comment by Geigerkind** [comment]
Alright, thank you sir!
