### ISSUE TITLE
Constant Debug error while using DPSmate - WoTLK

### ISSUE THREAD

**Issue by mario8000** [Geigerkind/Legacy-Logs-Bugtracker#43]
Date: 2016-12-31 16:43:51
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\DPSMate\DPSMate_Sync.lua line 1175:
   memory allocation error: block too big
Debug:
   [C]: ?
   DPSMate\DPSMate_Sync.lua:1175: HealingStatOut()
   DPSMate\DPSMate_Sync.lua:100: OnUpdate()
   DPSMate\DPSMate_DataBuilder.lua:2088:
      DPSMate\DPSMate_DataBuilder.lua:2039
AddOns:
  Swatter, v3.1.14 (<%codename%>)
  ACP, v3.2.0.118 
  Atlas, v1.17.0
  AtlasBattlegrounds, v1.17.0
  AtlasDungeonLocs, v1.17.0
  AtlasOutdoorRaids, v1.17.0
  AtlasTransportation, v1.17.0
  AtlasLoot, vv5.11.04
  AtlasLootFu, vv5.11.04
  AucAdvanced, v5.8.4723 (CreepyKangaroo)
  AucFilterBasic, v5.8.4723 (CreepyKangaroo)
  AucFilterOutlier, v5.8.4723.2531
  AucMatchUndercut, v5.8.4723.2531
  AucScanData, v5.8.4723 (CreepyKangaroo)
  AucStatHistogram, v5.8.4723 (CreepyKangaroo)
  AucStatiLevel, v5.8.4723 (CreepyKangaroo)
  AucStatPurchased, v5.8.4723 (CreepyKangaroo)
  AucStatSales, v5.8.4723.2842
  AucStatSimple, v5.8.4723 (CreepyKangaroo)
  AucStatStdDev, v5.8.4723 (CreepyKangaroo)
  AucStatWOWEcon, v5.8.4723.2530
  AucUtilAHWindowControl, v5.8.4723.3311
  AucUtilAppraiser, v5.8.4723.2530
  AucUtilAskPrice, v5.8.4723.3175
  AucUtilAutoMagic, v5.8.4723.3142
  AucUtilCompactUI, v5.8.4723.2530
  AucUtilEasyBuyout, v5.8.4723.3583
  AucUtilFixAH, v5.8.4723 (CreepyKangaroo)
  AucUtilGlypher, v5.8.4723.2545
  AucUtilItemSuggest, v5.8.4723.3108
  AucUtilPriceLevel, v5.8.4723.2545
  AucUtilScanButton, v5.8.4723.2530
  AucUtilScanFinish, v5.8.4723.3576
  AucUtilScanProgress, v5.8.4723.2530
  AucUtilScanStart, v5.8.4723.2530
  AucUtilSearchUI, v5.8.4723.3655
  AucUtilSimpleAuction, v5.8.4723.4546
  AucUtilVendMarkup, v5.8.4723.2530
  BeanCounter, v5.8.4723 (CreepyKangaroo)
  BlizzMove, vv0.7
  DBMCore, v
  DoomCooldownPulse, v
  DPSMate, v
  ElvUI, v5.25
  Flightmap, v
  GearScoreLite, v3x04
  Informant, v5.8.4723 (CreepyKangaroo)
  LootCouncilLite, v1.011
  Omen, v3.0.9
  QDKP2GUI, v2.6.7
  QDKPV2, v2.6.7
  SlideBar, v3.1.14 (<%codename%>)
  Stubby, v5.8.4723 (CreepyKangaroo)
  WIM, v3.3.7
  BlizRuntimeLib_enUS v3.3.5.30300 <logon.warmane.com>
  (ck=6e5)

**Comment by mario8000** [comment]
DPSMate is constantly making my other addons lag as well. Ex: WIM will take 60 seconds to send a whisper or longer!! QDKP will not allow me to start a after pressing "start bid" for extended peroid of time 60+seconds, or until I /reload. This needs fixed no wonder people cant/wont upload from WoTLK realms...

**Comment by Geigerkind** [comment]
Hey!
This seems to be a server related error. 
Also, did you increase your addon memory to atleast 150mb?

I assume you are using an addon, which will queue addon messages. Therefore I suggest to deactivate syncing by just pressing the green button beside the report button.

cheers!

**Comment by mario8000** [comment]
Addon memory is allocated automatically on WoTLK clients, there is no threshold like in vanilla client. I will try using it without sync turned on, but why else could I be receiving that error?

**Comment by Geigerkind** [comment]
Honestly I don't know. It might be the server that is preventing addon messages from being send and then it clocks up and therefore the memory overloads.
Need to look into it

**Comment by mario8000** [comment]
Date: 2017-01-02 20:12:55
ID: 1
Error occured in: Global
Count: 2
Message: ..\FrameXML\UIDropDownMenu.lua line 836:
   attempt to index local 'frame' (a number value)
Debug:
   [C]: ?
   ..\FrameXML\UIDropDownMenu.lua:836: UIDropDownMenu_SetWidth()
   [string "*:OnLoad"]:4:
      [string "*:OnLoad"]:1
AddOns:
  Swatter, v3.1.14 (<%codename%>)
  ACP, v3.2.0.118 
  Atlas, v1.17.0
  AtlasBattlegrounds, v1.17.0
  AtlasDungeonLocs, v1.17.0
  AtlasOutdoorRaids, v1.17.0
  AtlasTransportation, v1.17.0
  AtlasLoot, vv5.11.04
  AtlasLootFu, vv5.11.04
  AucAdvanced, v5.8.4723 (CreepyKangaroo)
  AucFilterBasic, v5.8.4723 (CreepyKangaroo)
  AucFilterOutlier, v5.8.4723.2531
  AucMatchUndercut, v5.8.4723.2531
  AucStatHistogram, v5.8.4723 (CreepyKangaroo)
  AucStatiLevel, v5.8.4723 (CreepyKangaroo)
  AucStatPurchased, v5.8.4723 (CreepyKangaroo)
  AucStatSales, v5.8.4723.2842
  AucStatSimple, v5.8.4723 (CreepyKangaroo)
  AucStatStdDev, v5.8.4723 (CreepyKangaroo)
  AucStatWOWEcon, v5.8.4723.2530
  AucUtilAHWindowControl, v5.8.4723.3311
  AucUtilAppraiser, v5.8.4723.2530
  AucUtilAskPrice, v5.8.4723.3175
  AucUtilAutoMagic, v5.8.4723.3142
  AucUtilCompactUI, v5.8.4723.2530
  AucUtilEasyBuyout, v5.8.4723.3583
  AucUtilFixAH, v5.8.4723 (CreepyKangaroo)
  AucUtilGlypher, v5.8.4723.2545
  AucUtilItemSuggest, v5.8.4723.3108
  AucUtilPriceLevel, v5.8.4723.2545
  AucUtilScanButton, v5.8.4723.2530
  AucUtilScanFinish, v5.8.4723.3576
  AucUtilScanProgress, v5.8.4723.2530
  AucUtilScanStart, v5.8.4723.2530
  AucUtilSearchUI, v5.8.4723.3655
  AucUtilSimpleAuction, v5.8.4723.4546
  AucUtilVendMarkup, v5.8.4723.2530
  BeanCounter, v5.8.4723 (CreepyKangaroo)
  BlizzMove, vv0.7
  DBMCore, v
  DoomCooldownPulse, v
  DPSMate, v
  SlideBar, v3.1.14 (<%codename%>)
  Stubby, v5.8.4723 (CreepyKangaroo)
  BlizRuntimeLib_enUS v3.3.5.30300 <logon.warmane.com>
  (ck=603)

Another debug error i'm receiving when having armory/dpsmate enabled.

**Comment by Geigerkind** [comment]
Did it occour once you logged in or when you did something?

**Comment by mario8000** [comment]
Instantly on login

**Comment by Geigerkind** [comment]
Alright, will check it, could you upload your addon pack here?

**Comment by mario8000** [comment]
All of my active addons are listed in that debug error. Do you still need my addons sent to you?

**Comment by Geigerkind** [comment]
This would be the easiest to just wrap your interface folder and put it here. See it would take a lot of time to look up every addon at every specific version^^
This would just make things a lot easier for me :>

**Comment by Geigerkind** [comment]
This was a complicated one. Without your upload I wouldn't have been able to reproduce this bug. 
Thanks a lot!

**Comment by mario8000** [comment]
Has the bug fix been uploaded/packaged?

**Comment by mario8000** [comment]
Also has the issues with the addon making other addons lag been fixed?

**Comment by Geigerkind** [comment]
Yes, and the other is server dependet. Can't really fix that, so I suggest to deactivate syncing anyway. I guess I should remove that feature for wotlk anyway, since it is not required anymore.
