### ISSUE TITLE
Java-launcher doesn't upload logs.

### ISSUE THREAD

**Issue by theExile015** [Geigerkind/Legacy-Logs-Bugtracker#59]
Got problems with logs uploading with java launcher both exe and jar (not only me, but 3 guildmates too). Another one uploads correctly (but too slow imo).
Launcher v.29

Cheers, Anri
Kronos 1

**Comment by Geigerkind** [comment]
Hey! 
The server crashed at this time. Can you confirm this please again?

cheers!

**Comment by theExile015** [comment]
Yes, java client show message "upload complite", but it doesn't show up on current queue page. With another clinet everything is ok.

**Comment by 45270689** [comment]
java client show message "upload complite", but it doesn't show up on current queue page. With another clinet is not work.why?

**Comment by 45270689** [comment]
raidstats cant be uploaded

**Comment by 45270689** [comment]
it said "input string was not is a correct format"

**Comment by Geigerkind** [comment]
Ok, will look into it. Use the normal one in the meanwhile if you can.

**Comment by 45270689** [comment]
i cant upload date  when i check reupload is said  "input string was not is a correct format"

**Comment by Geigerkind** [comment]
Should be fixed. Thanks for the report!
