### ISSUE TITLE
Viele ungute bugs nach wie vor

### ISSUE THREAD

**Issue by thexeuss** [Geigerkind/Legacy-Logs-Bugtracker#61]
Hey!

Ich hatte deine twitter seite verfolgt, du hattest viele probleme mit server etc.
Daher ist es verständlich das du prioritäten setzen musst.

Wenn du wieder die möglichkeit hast was zu fixen, bitte schau dir gleich mal die Hunter und ihre Pets an.
Der DMG von den Pets wird schon seit wochen nicht mehr mitgerechnet.

Der Launcher funktioniert mit stand heute (15.1 22:00) garnicht mehr. Es wird gesagt:
Neue version runterladen!

Aber eine neue version über den link gibt den selben fehler.

Den letzten combatlog den ich aufgezeichnet hab, wurde auch nicht eingestellt, ich fügen den hier mal rein.

[DPSMate-Save-Euss-15-21-57-2017.lua.gz](https://github.com/Geigerkind/Legacy-Logs-Bugtracker/files/706919/DPSMate-Save-Euss-15-21-57-2017.lua.gz)

soweit mal..
Beste grüße

**Comment by Geigerkind** [comment]
Hey!
Ich meine vor 2 Tagen den Bug mit dem Launcher gefixxt zu haben. War allerdings nach 22 Uhr glaub ich. 
Hast du immernoch Probleme mit dem uploaden?

Das mit den Pets schaue ich mir mal an die Tage.

Zu den Prioritäten:
Ich schreibe in ein paar Wochen Klausuren in der Uni und kann deswegen, wenn nur am Wochenende ein wenig an Legacy Logs arbeiten.
Außerdem gibt es viel noch daneben zu tun, also verzeih, wenn Dinge ein dauern, um gefixt zu werden^^
Arbeite leider nur alleine an dem Projekt und habe momentan eine 70 Stunden Woche, die mich mehr als fertig macht. Vor allem, wenn ich nochmal 20 am Wochenende drauf setze für all meine Projekte.

cheers!

**Comment by thexeuss** [comment]
Das mit dem real life projekten geht klar vor, keine frage!
Danke auch für deine arbeit soweit!

Hatte gestern (16.1) den launcher geladen, da war das erstellungsdatum noch 15.1 16:05
Heute 17.1 nochmal geladen, der launcher hat nun erstellungsdatum 15.1 20:45
Der neuere launcher funktioniert jetzt wieder, danke.

den log kann ich trozdem nicht mehr hochladen, RIP..

Die Pets fehlen bei uns schon seit einigen wochen, danke fürs drüberschauen!

Was hier wirklich noch fehlt und geil wäre:
Eine etwas detailiertere übersicht über die tode von spielern.
Eine übersicht von den buff/debuff uptimes wie zb. feenfeuer und schwäche aufdecken.

Falls du nach den klausuren zeit hast und ziele brauchst ^^

Hoffentlich überstehst du die klausurenzeit, ich wünsche dir da das beste!
grüße

**Comment by Geigerkind** [comment]
Hab den Log mal manuell hochgeladen
