### ISSUE TITLE
Teron Gorefiend taucht nicht in den Logs auf (Black Temple)

### ISSUE THREAD

**Issue by armaggedon1** [Geigerkind/Legacy-Logs-Bugtracker#63]
Hey,
Teron Gorefiend taucht leider seit längerem (nicht mehr?) in den Logs auf.

Hier mal der Log von meinem letzten Bt Raid:
[DPSMate-Save-Kknd-19-01-17-21-48-46.lua.gz](https://github.com/Geigerkind/Legacy-Logs-Bugtracker/files/717803/DPSMate-Save-Kknd-19-01-17-21-48-46.lua.gz)

Gruß

**Comment by armaggedon1** [comment]
Was mir noch aufgefallen ist: Der Link zu Teron unter Speedkills führt zu Doom Lord Kazzak
https://www.legacy-logs.com/TBC/Speed-Kills/Ranking/?server=0&faction=0&mode=0&id=5

**Comment by Geigerkind** [comment]
Fixed
