### ISSUE TITLE
Losing healing data in logs

### ISSUE THREAD

**Issue by jockeboschko** [Geigerkind/Legacy-Logs-Bugtracker#69]
For the last two raids we have done healing has not been uploaded. We have around 7 people syncing.
Dispells seem to be incorrect but i guess that is because we aren't 40 people syncing. Me and all the other people syncing got version 90 and latest logging software.
Here are the links:
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=4432
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=4393

**Comment by Geigerkind** [comment]
Fixed!
