### ISSUE TITLE
Damage taken no stats only graph

### ISSUE THREAD

**Issue by jockeboschko** [Geigerkind/Legacy-Logs-Bugtracker#72]
Hello, the logs i am uploading dont have the text format of damage taken only the graph. Worked on older logs on kronos but not elysium. Maybe its elysium related.

Also Titans of War is still on speedruns on elysium although i think they were on the old server because they have dps that is not possible right now(and doing bwl).

https://legacy-logs.com/Vanilla/Raids/Evaluation/DmgTaken/index.php?rid=4688&attempts=226888,226898,226901,226907,226919,226922,226926,226935,226947,226952&player=64064&sel=0&pet=0&tarid=&mode=2

**Comment by Geigerkind** [comment]
ok, will look into it after my exams.
Thanks for the report!

**Comment by Geigerkind** [comment]
Fixed!
