### ISSUE TITLE
Long title section breaks subcategory onhover buttons

### ISSUE THREAD

**Issue by Mitheren** [Geigerkind/Legacy-Logs-Bugtracker#74]
When the title section (Raid, uploaders, dates, guild, server) are too long, they push the guild and server name down which moves the category buttons. This in turns makes it impossible to click on the onhover subcategory buttons.

Example:

![image](https://cloud.githubusercontent.com/assets/899847/23440852/e54027c2-fe72-11e6-88c0-97f7aeea0748.png)

from this page: https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=4422

**Comment by Geigerkind** [comment]
Fixed
