### ISSUE TITLE
Shown as Hord but we are Alliance

### ISSUE THREAD

**Issue by chrheg** [Geigerkind/Legacy-Logs-Bugtracker#77]
#5913 ( MC Raid )Upload Shows us as Hords but the correct is Alliance.

#5927 ( Ony Raid ) Upload shows correct data.

Any chance to fix it some that the #5913 is correct ?

**Comment by Krabator** [comment]
Hello Geigerkind,

Same for my guild <Aube>
We are alliance but we are now recorded as a Horde guild
https://legacy-logs.com/Vanilla/Raids/?name=Aube&date=&duration=&realm=9&faction=0&raid=0

**Comment by Geigerkind** [comment]
Fixed it a few days ago. I can't associate the horde guilds to the alliance guilds now anymore
