### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by eddiehunter17** [Geigerkind/Legacy-Logs-Bugtracker#81]
When I'm trying to View a character on leglogs I get this:

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY item' at line 1 in /home/legacylo/public_html/Database/Database.php:150 Stack trace: #0 /home/legacylo/public_html/Database/Database.php(150): PDO->query('SELECT item, CO...') #1 /home/legacylo/public_html/Vanilla/Armory/index.php(244): Database->query('SELECT item, CO...') #2 /home/legacylo/public_html/Vanilla/Armory/index.php(1272): Home->getItemTemplate(Object(Mysql)) #3 /home/legacylo/public_html/Vanilla/Armory/index.php(1286): Home->__construct(Object(Mysql), '/home/legacylo/...', 'ZethKur', 'Zazoom', '0') #4 {main} thrown in /home/legacylo/public_html/Database/Database.php on line 150

Some characters can be seen tho.

Same with guilds:

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY grankindex, seen DESC, name LIMIT 0, 50' at line 1 in /home/legacylo/public_html/Database/Database.php:150 Stack trace: #0 /home/legacylo/public_html/Database/Database.php(150): PDO->query('SELECT name, cl...') #1 /home/legacylo/public_html/Vanilla/Guild/index.php(629): Database->query('SELECT name, cl...') #2 /home/legacylo/public_html/Modules/Site.php(168): Home->content() #3 /home/legacylo/public_html/Modules/Site.php(182): Site->run() #4 /home/legacylo/public_html/Vanilla/Guild/index.php(718): Site->__construct(Object(Mysql), '/home/legacylo/...') #5 /home/legacylo/public_html/Vanilla/Guild/index.php(722): Home->__construct(Object(Mysql), '/home/legacylo/...', 'Dice Roll', 'Zeth'Kur', '0', NULL, NULL, NULL, NULL) #6 {main} thrown in /home/legacylo/public_html/Database/Database.php on line 150

**Comment by eddiehunter17** [comment]
Edit: happens only for zeth'kur server characters/guilds so far

**Comment by RussianE39** [comment]
I suppose problem with realm name - look at ZK realm name. Thats why we have SQL syntax error.

**Comment by Geigerkind** [comment]
Fixed. Thy!
