### ISSUE TITLE
Twin Emperors missing in AQ40

### ISSUE THREAD

**Issue by Baraz** [Geigerkind/Legacy-Logs-Bugtracker#83]
Apparently the fight with the Twin Emps is not properly recorded or displayed. 
For example: https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=8027
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=8024
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=7968
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=7806
You can't kill Ouro and C'thun without killing the Twins first. The last recorded fight uploaded that i found (https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=5353) is from 05.03.2017, maybe that helps to find the changes.

**Comment by Geigerkind** [comment]
Should be fixed now!

**Comment by Baraz** [comment]
The last upload had the Twin fight displayed again, seems good now. Thank you!
