### ISSUE TITLE
SQL errors on almost any page around Zeth'Kur realm

### ISSUE THREAD

**Issue by RussianE39** [Geigerkind/Legacy-Logs-Bugtracker#87]
How to reproduce:
https://legacy-logs.com/Vanilla/Guild/Zeth'Kur/PugRaid/0

Error message:

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY grankindex, seen DESC, name LIMIT 0, 50' at line 1 in /home/legacylo/public_html/Database/Database.php:150 Stack trace: #0 /home/legacylo/public_html/Database/Database.php(150): PDO->query('SELECT name, cl...') #1 /home/legacylo/public_html/Vanilla/Guild/index.php(629): Database->query('SELECT name, cl...') #2 /home/legacylo/public_html/Modules/Site.php(168): Home->content() #3 /home/legacylo/public_html/Modules/Site.php(182): Site->run() #4 /home/legacylo/public_html/Vanilla/Guild/index.php(718): Site->__construct(Object(Mysql), '/home/legacylo/...') #5 /home/legacylo/public_html/Vanilla/Guild/index.php(722): Home->__construct(Object(Mysql), '/home/legacylo/...', 'PugRaid', 'Zeth'Kur', '0', NULL, NULL, NULL, NULL) #6 {main} thrown in /home/legacylo/public_html/Database/Database.php on line 150

Comments: I suppose problem from ' symbol in realm name

**Comment by 08freaxy** [comment]
it would be nice if this can be fixed.

**Comment by Geigerkind** [comment]
Sorry about that, I really wish I had more time for this :<

**Comment by RussianE39** [comment]
You're my hero! Thanks!
