### ISSUE TITLE
Missing uploads on Nefarian

### ISSUE THREAD

**Issue by Baraz** [Geigerkind/Legacy-Logs-Bugtracker#88]
Since the 23.04.2017 (and even before that a couple of times on different characters) my data is not uploaded. It is shown in the queue to be processed, but afterwards it is not displayed on the page. Could you check if it is something on my side or if it has something to do with the processing/merging/database-stuff?

[DPSMate-Save-Barazanthul-30-04-17-23-58-24.lua.gz](https://github.com/Geigerkind/Legacy-Logs-Bugtracker/files/967531/DPSMate-Save-Barazanthul-30-04-17-23-58-24.lua.gz)

**Comment by l1amm** [comment]
Same issue here on Elysium. Raid nights were even updated after it finished in the queue but no logs =/

**Comment by Baraz** [comment]
I think it could be in connection to raids where I logged out during the raid, either because of saving buff time or because of servercrashes. Is DPSMate able to recover from that?

**Comment by Baraz** [comment]
Anecdotal evidence over the last weeks indeed suggest, that is connected to the Logout. Raids where I didn't log out were uploaded correctly, otherwise they were not.

**Comment by BugsBugs** [comment]
I issue the same problem. As long as i dont hace any disconnects or log outs it works fine. Is there a workaround how to upoloas logs even if i had dc?

**Comment by Geigerkind** [comment]
Normally that should not result in an issue, need to investigate this further.
Im sorry for the delay. Im incredibly busy currently :<

**Comment by Geigerkind** [comment]
Should be resolved now. Please comment below if it occours again!

**Comment by Geigerkind** [comment]
Found the issue!
Fixed!
