### ISSUE TITLE
Bossfight "Bug Trio" is missing

### ISSUE THREAD

**Issue by BugsBugs** [Geigerkind/Legacy-Logs-Bugtracker#90]
Hello,

I uploaded our log from AQ40 last night. unfortunately the Fight against the Bug Trio is not listed. 

Also there are no Dispels type posion listed.

https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=9984

We are about 8 people with DPSMate and I am the only one who is uploading. Is this the reason? Because I had a look into other raids and it seems that the Bug Trio never appears.

Also I would like to ask a question about the sync: If every Player activates sync on DPSMate(and we clear DPSmate at Raidstart), the data of our logs should all be same right? So it doesnt matter how many people upload to legacy-logs, right? Thanks a lot for you work !

Greetings

**Comment by Geigerkind** [comment]
Should be fixed now!
