### ISSUE TITLE
Raidstats will not upload

### ISSUE THREAD

**Issue by Cetus91** [Geigerkind/Legacy-Logs-Bugtracker#92]
Hello,

Since may 16th I have been unsuccesful in uploading any logs. The only thing that seems to update is the armory and some items received, but no raid stats. The most recent log can be found here :http://s000.tinyupload.com/?file_id=31057332908636221578

I am using DPSmate B117 with the latest launcher. Any idea as to the cause of this?
My character is Cetus on Anathema, should you want to look me up there.

Thank you in advance.

**Comment by Geigerkind** [comment]
Fixed!
