### ISSUE TITLE
Disconnects/relogging bug DPSMate and the log

### ISSUE THREAD

**Issue by rejaa** [Geigerkind/Legacy-Logs-Bugtracker#94]
1. Where has is happened?
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=12257

2. When did it happen?
7/6/2017 around 19:05

3. Under which circumstances did it happen?
I started the client when logging in for raid invite after which i logged out again and waited for raid start.
When i logged in i got disconnected on the loading screen and it brought me back to the login screen.
I try to log in again and this time it works.
As soon as we start doing trash in AQ40 i notice that i can only see myself and one other rogue on the DPSMate addon, which i found fairly strange.
I exited my WoW client after the first trash pack creating an upload to legacy log.
I restarted the LL client and my WoW client through that.
DPSMate was still only showing only myself and one other rogue.
Raid continues and i'm pretty bummed that i can't really see anything on the addon, but ok..
We wipe on Viscidus and as soon as i re-entered from corpse running, the addon suddenly showed perfectly, everything was logged, including previous bosses.
We end the raid with C'thun and go to Onyxia, kill her so when getting back to orgrimmar i exit my client to upload to log.
Onyxia log seems fine: https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=12258
AQ40 log is completely bugged: https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=12257
and it didn't get synced with one other guy who was also tracking: https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=12252
His log for AQ40 seems ok.

4. Do you know how to reproduce the bug?
I guess if you force disconnect your WoW client which is running through the LL client, you will force this sort of bug.
I got randomly disconnected when logging in though.
But i've noticed DPSMate not showing everything when i relog as well.

I've added the log
[DPSMate-Save-Stabzes-07-21-32-2017.lua.gz](https://github.com/Geigerkind/Legacy-Logs-Bugtracker/files/1059372/DPSMate-Save-Stabzes-07-21-32-2017.lua.gz)

5. Has there been an error message, if so, please provide it
No error message

**Comment by Geigerkind** [comment]
This is a bug of DPSMate^^
I will look into that. I assume that has to do with high server latency on loadup.

**Comment by Geigerkind** [comment]
Please report back if the error still occours in B123.
